### ISSUE TITLE
Download roads network from OSM

### ISSUE THREAD

**Issue by edarin** [GISRedeDev/PyNetworkFriction#22]
This would be an enhamcement for this package (and not a requirement).
It would consist in creating a similar function as `get_acled_data_from_api` for downloading the road network of a country from OSM.

**Comment by GISRedeDev** [comment]
Let me think about this a bit. I don't really want to go out of the scope of the package's functionality because it ties me in to having to monitor additional packages. I don't really want to add functionality that is already available elsewhere. For now, I will add something in the docs pointing to a python package that does this already.
