### ISSUE TITLE
Buffer in `get_incidents_in_route_sjoin`

### ISSUE THREAD

**Issue by edarin** [GISRedeDev/PyNetworkFriction#23]
I'm wondering if we need to specify a buffer in the function `get_incidents_in_route_sjoin` as it seems that `subset_incident_data_in_buffer` would have already taken care of it.

I am guessing that we might want to have a default upper buffer to avoid computation issue. And maybe a print that tell the user what is the default value.

https://github.com/GISRedeDev/PyNetworkFriction/blob/16ecf5695bc47272a30ab2124ca8e7fa16cc658a/net_friction/calculations.py#L172

**Comment by GISRedeDev** [comment]
I've taken a look and I think I realise now why I did it like this. The first buffer eliminates points that we don't want in the analysis. The second buffer is done because the points need to be joined to the edges to which they are associated, rather then the whole edge dataset (for example, we need a table that says `incident_1` joins `edge_1` and `edge_2` - we don't get this information on the original join). I don't think this should slow things down too much, but even if it does, it is required.

I will close this issue now, but if you don't agree let me know and we can come back to it.
